// Tool: save_audit_report
// Render an audit_page / audit_site result as Markdown and write to a workspace file.
// Restricted to the directory tree under MCP_WORKSPACE_ROOT (or cwd if unset).

import { z } from "zod";
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, isAbsolute, resolve, sep, relative } from "node:path";
import type { Finding } from "../types.js";
import type { AuditPageResult } from "./audit-page.js";
import type { AuditSiteResult } from "./audit-site.js";

export const saveAuditReportInputSchema = z.object({
  audit_result: z.unknown().describe("The return value of audit_page or audit_site"),
  path: z.string().min(1).describe("Target file path. May be relative to MCP_WORKSPACE_ROOT (or cwd)."),
  overwrite: z.boolean().optional().default(true),
});

export type SaveAuditReportInput = z.infer<typeof saveAuditReportInputSchema>;

export interface SaveAuditReportResult {
  saved_to: string;
  bytes_written: number;
  format: "audit_page" | "audit_site";
}

function severityEmoji(s: Finding["severity"]): string {
  return s === "critical" ? "🔴" : s === "warning" ? "🟡" : "🔵";
}

function findingsToTable(findings: Finding[]): string {
  if (findings.length === 0) return "_No findings._\n";
  const rows = findings.map((f) => {
    const impact = f.estimated_impact ? ` (impact: ${f.estimated_impact})` : "";
    return `### ${severityEmoji(f.severity)} ${f.category} — ${f.message}\n\n` +
      `**Where:** \`${f.where}\`${impact}\n\n` +
      `**Fix:** ${f.fix}\n`;
  });
  return rows.join("\n");
}

function citationVerdict(grade: AuditPageResult["grade"]): string {
  switch (grade) {
    case "A": return "🟢 Highly citation-ready. AI assistants are likely to surface this page.";
    case "B": return "🟢 Citation-ready with minor gaps. A few fixes will lift you into top-tier.";
    case "C": return "🟡 Mixed signals. Several structural / authority issues are likely blocking citations.";
    case "D": return "🟠 Low citation readiness. Multiple critical issues must be addressed.";
    case "F": return "🔴 Not citation-ready. AI engines are likely skipping this page.";
  }
}

function dimensionTable(scores: AuditPageResult["dimension_scores"]): string {
  const rows: string[] = ["| Dimension | Score |", "|---|---|"];
  for (const [k, v] of Object.entries(scores)) {
    rows.push(`| ${k} | ${v}/100 |`);
  }
  return rows.join("\n");
}

function isAuditPage(x: unknown): x is AuditPageResult {
  return !!x && typeof x === "object" && "dimension_scores" in x && "grade" in x && "findings" in x;
}

function isAuditSite(x: unknown): x is AuditSiteResult {
  return !!x && typeof x === "object" && "top_5_fixes" in x && "overall_grade" in x && "parts" in x;
}

function renderAuditPage(r: AuditPageResult): string {
  const sorted = [...r.findings].sort((a, b) => {
    const rank = (s: Finding["severity"]) => (s === "critical" ? 0 : s === "warning" ? 1 : 2);
    return rank(a.severity) - rank(b.severity);
  });
  return [
    `# AI-SEO audit: ${r.url}`,
    ``,
    `> ${citationVerdict(r.grade)}`,
    ``,
    `**Score:** ${r.score}/100 (grade ${r.grade})`,
    `**Fetched:** ${r.fetched_at}`,
    `**Content quality:** \`${r.content_quality}\``,
    ``,
    `## Dimension scores`,
    ``,
    dimensionTable(r.dimension_scores),
    ``,
    `## Findings (${r.findings.length})`,
    ``,
    findingsToTable(sorted),
    ``,
    `---`,
    ``,
    `_Generated by [@automatelab/ai-seo-mcp](https://github.com/AutomateLab-tech/ai-seo)._`,
    ``,
  ].join("\n");
}

function renderAuditSite(r: AuditSiteResult): string {
  return [
    `# AI-SEO site audit: ${r.domain}`,
    ``,
    `**Overall score:** ${r.overall_score}/100 (grade ${r.overall_grade})`,
    `**Homepage:** ${r.homepage_url}`,
    `**Fetched:** ${r.fetched_at}`,
    ``,
    `## Top 5 fixes`,
    ``,
    findingsToTable(r.top_5_fixes),
    ``,
    `## Components`,
    ``,
    `- \`audit_page\`: ${"error" in r.parts.audit_page ? `❌ ${r.parts.audit_page.error}` : `${r.parts.audit_page.score}/100`}`,
    `- \`check_robots\`: ${"error" in r.parts.check_robots ? `❌ ${r.parts.check_robots.error}` : r.parts.check_robots.recommended_posture}`,
    `- \`check_sitemap\`: ${"error" in r.parts.check_sitemap ? `❌ ${r.parts.check_sitemap.error}` : r.parts.check_sitemap.status}`,
    `- \`audit_schema\`: ${"error" in r.parts.audit_schema ? `❌ ${r.parts.audit_schema.error}` : `${r.parts.audit_schema.ai_citation_readiness_score}/100`}`,
    ``,
    `---`,
    ``,
    `_Generated by [@automatelab/ai-seo-mcp](https://github.com/AutomateLab-tech/ai-seo)._`,
    ``,
  ].join("\n");
}

function resolveSafePath(target: string): string {
  const workspaceRoot = resolve(process.env["MCP_WORKSPACE_ROOT"] ?? process.cwd());
  const absolute = isAbsolute(target) ? resolve(target) : resolve(workspaceRoot, target);
  const rel = relative(workspaceRoot, absolute);
  if (rel.startsWith("..") || rel.includes(`..${sep}`) || isAbsolute(rel)) {
    throw new Error(
      `path "${target}" escapes MCP_WORKSPACE_ROOT (${workspaceRoot}). Set MCP_WORKSPACE_ROOT or pass a path inside it.`
    );
  }
  return absolute;
}

export async function saveAuditReport(input: SaveAuditReportInput): Promise<SaveAuditReportResult> {
  let markdown: string;
  let format: "audit_page" | "audit_site";

  if (isAuditSite(input.audit_result)) {
    markdown = renderAuditSite(input.audit_result);
    format = "audit_site";
  } else if (isAuditPage(input.audit_result)) {
    markdown = renderAuditPage(input.audit_result);
    format = "audit_page";
  } else {
    throw new Error(
      "audit_result does not look like an audit_page or audit_site output (missing expected fields)."
    );
  }

  const absolute = resolveSafePath(input.path);
  await mkdir(dirname(absolute), { recursive: true });
  await writeFile(absolute, markdown, { encoding: "utf8", flag: input.overwrite ? "w" : "wx" });

  return {
    saved_to: absolute,
    bytes_written: Buffer.byteLength(markdown, "utf8"),
    format,
  };
}
